name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo & submodules
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Run tests
      uses: ./.github/actions/docker
      with:
        script: |
          rustup default stable
          cargo build --verbose
          cargo test --verbose